version: '3.12'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000 & wait"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - '5433'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=biotact.settings
    networks:
      - backend
  bot:
    build: .
    restart: always
    command: sh -c "python main.py & wait"
    volumes:
      - .:/app
    depends_on:
      - web
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=biotact.settings
    networks:
      - backend

  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=LO1Fgj4aVR
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
