# Generated by Django 5.0.6 on 2024-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_usercart_promocode_alter_usercart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='products',
        ),
        migrations.AddField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
