# Generated by Django 5.0.6 on 2024-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_usercart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='products',
        ),
        migrations.AddField(
            model_name='usercart',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
