# Generated by Django 5.0.6 on 2024-05-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_usercart_products_usercart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('promocode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Использованный промокод',
                'verbose_name_plural': 'Использованные промокоды',
            },
        ),
    ]
