# Generated by Django 5.0.6 on 2024-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_usedpromocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='code',
            new_name='promocode_code',
        ),
    ]
