# Generated by Django 5.0.6 on 2024-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_code_promocode_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
