# Generated by Django 5.0.6 on 2024-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_merchant_product_is_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_merchant',
            new_name='is_merch',
        ),
    ]
