# Generated by Django 5.0.6 on 2024-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_is_merchant_product_is_merch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('order_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='CategoryProducts',
        ),
        migrations.AddField(
            model_name='usertg',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
