# Generated by Django 5.0.6 on 2024-07-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_myorders_order_text_alter_useraddress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_merch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_set',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('product', 'Продукт'), ('set', 'Сет')], default='product', max_length=10),
        ),
    ]
