# Generated by Django 5.0.6 on 2024-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_is_merch_remove_product_is_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('product', 'Продукт'), ('set', 'Эксклюзивные сеты'), ('merch', 'Мерч')], default='product', max_length=10),
        ),
    ]
