# Generated by Django 5.0.6 on 2024-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время истечения промокода', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='expiration_time',
            field=models.DurationField(blank=True, help_text='Продолжительность действия промокода (в днях)', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='expiration_type',
            field=models.CharField(choices=[('time', 'По времени'), ('date', 'По дате')], default='time', max_length=4),
        ),
    ]
